import Head from 'next/head'



const Layout = ({children, title = "Crypto Tracker"}) => {
     return (
         <div className='layout'>
          <Head>
           <title>{title}</title>
           <meta name="description" content="Generated by create next app" />
           <link rel="icon" href="/favicon.ico" />
          </Head>

             <div>
	              <h1>Club del crypto</h1>
		
	        </div>
        
               <main>{children}</main>

         </div>
     )
}

export default Layout;